### ISSUE TITLE
maglit.me has a few a11y issues

### ISSUE THREAD

**Issue by aloisdg** [NayamAmarshe/thiss.link#72]
Hello,

I would like to use maglit.me but first I would like to know if anyone is working to improve maglit accessibility. By running an axe scan I found a bunch of issue:

![image](https://github.com/user-attachments/assets/cc7ff0e2-2c00-4a4b-be38-ea03b5e72c49)

If none, I may start it myself this weekend

**Comment by aloisdg** [comment]
@NayamAmarshe alright. Any reason why?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe alright. Any reason why? (You dont have to answer if you dont want to)

Scammers driving the costs of hosting. With the current rate, it would cost hundreds of dollars each month to run MagLit.

I'm going to switch to another project: 'thiss.link' instead. It'll be a new website and will support old MagLit links and will have a new interface.
